/*  ==================================================================================================================*\
 *   Ben Mariem Sami - Derroitte Natan - Testouri Mehdi -     Project  - O.O.S.E
 *
 *    GUIError class
\*  ==================================================================================================================*/
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;

/**
 *
 * Made via NetBeans
 */
public class GUIError extends GUI
{
    //Variables.
    private String errorText;
    private javax.swing.JLabel error;
    private javax.swing.JPanel jPanel;

    /**
     * Constructor of the class
     * @param inputError : A string containing the error.
     * @see GUIInstantiation
     */
    public GUIError(String inputError)
    {
        errorText = inputError;
        initComponents();
    }

    /**
     *
     * @return
     */
    private int handleClose()
    {
        if(errorText.equals(Constants.CONNECTION_TIMEOUT_ERROR) || errorText.equals(Constants.BAD_REQUEST_LOGIN)
                || errorText.equals(Constants.INVALID_PASSWORD_ERROR) ||
                errorText.equals(Constants.BLACKLISTED_CLIENT_ERROR) || errorText.equals(Constants.CONNECTION_LOST))
            return javax.swing.WindowConstants.EXIT_ON_CLOSE;
        return 1;
    }
    /**
     * This piece of code was auto-generated by the NetBeans 8.1 IDE.
     * @see GUI
     */
    protected void initComponents()
    {
        jPanel = new javax.swing.JPanel();
        error = new javax.swing.JLabel();

        setDefaultCloseOperation(handleClose());
        setTitle("Error!");
        setBackground(new java.awt.Color(233, 234, 212));

        jPanel.setBackground(new java.awt.Color(233, 234, 212));
        error.setText("Error : "+errorText);

        //Changing Font.
        try
        {
            InputStream myStream = new BufferedInputStream(new FileInputStream(Police));
            Font font = Font.createFont(Font.TRUETYPE_FONT, myStream);
            Font sizedFont = font.deriveFont(28f);
            error.setFont(sizedFont);
        }
        catch(FontFormatException e)
        {
            System.err.println("FontFormatException: " + e.getMessage());
        }
        catch (IOException e)
        {
            System.err.println("Caught IOException: " + e.getMessage());
        }

        //Setting Layout.
        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(error)
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(error)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }
}
